// ============================================================
// Demo / Mock data for development and presentations
// Used when Supabase is not configured or DEMO_MODE=true
// ============================================================

import type {
  Location,
  SafetyRating,
  SafetyAlert,
  IncidentReport,
  EmergencyContact,
  LocalRecommendation,
  ChatMessage,
  Profile,
  SOSAlert,
} from '@/types';

// ---- Comprehensive 22+ Famous Destinations in India ----

export const DEMO_LOCATIONS: Location[] = [
  // 1. Chennai City
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    name: 'Chennai City',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 13.0827,
    longitude: 80.2707,
    description: 'The cultural capital of South India, known for classical music, Dravidian temples, and long sandy beaches.',
    timezone: 'Asia/Kolkata',
    population: 10971108,
    area_km2: 426,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 2. Marina Beach
  {
    id: 'e5f6a7b8-c9d0-1234-efab-345678901234',
    name: 'Marina Beach',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 13.0499,
    longitude: 80.2824,
    description: 'One of the longest natural urban beaches in the world, stretching over 13 km with coastal food stalls and heritage statues.',
    timezone: 'Asia/Kolkata',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 3. Mahabalipuram
  {
    id: 'loc-mahabalipuram',
    name: 'Mahabalipuram Shore Temple',
    city: 'Mahabalipuram',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 12.6269,
    longitude: 80.1927,
    description: 'UNESCO World Heritage site featuring 7th-century rock-cut monuments, Pancha Rathas, and the iconic coastal Shore Temple.',
    timezone: 'Asia/Kolkata',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 4. Nellore
  {
    id: 'loc-nellore',
    name: 'Nellore',
    city: 'Nellore',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 14.4426,
    longitude: 79.9865,
    description: 'Historic city situated on the banks of Penna River, famous for Sri Ranganathaswamy Temple, Mypadu Beach, and aquaculture.',
    timezone: 'Asia/Kolkata',
    population: 600000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 5. Tirupati
  {
    id: 'loc-tirupati',
    name: 'Tirupati (Tirumala)',
    city: 'Tirupati',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 13.6288,
    longitude: 79.4192,
    description: 'World-renowned spiritual city at the foot of Seshachalam Hills, home to Sri Venkateswara Temple with round-the-clock pilgrim security.',
    timezone: 'Asia/Kolkata',
    population: 459985,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 6. Visakhapatnam
  {
    id: 'loc-vizag',
    name: 'Visakhapatnam (Vizag)',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 17.6868,
    longitude: 83.2185,
    description: 'Scenic port city known for RK Beach, INS Kursura Submarine Museum, Kailasagiri hill park, and Rushikonda Beach.',
    timezone: 'Asia/Kolkata',
    population: 2300000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 7. Hyderabad
  {
    id: 'loc-hyderabad',
    name: 'Hyderabad (Charminar & Hi-Tech City)',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    latitude: 17.3850,
    longitude: 78.4867,
    description: 'City of Pearls blending historic monuments like Golconda Fort and Charminar with cyber tech corridors and famous Hyderabadi Biryani.',
    timezone: 'Asia/Kolkata',
    population: 10500000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 8. Bengaluru
  {
    id: 'd4e5f6a7-b8c9-0123-defa-234567890123',
    name: 'Bengaluru City',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    latitude: 12.9716,
    longitude: 77.5946,
    description: 'The Silicon Valley of India, known for pleasant weather, lush green gardens (Lalbagh, Cubbon Park), and bustling nightlife.',
    timezone: 'Asia/Kolkata',
    population: 13193000,
    area_km2: 741,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 9. Mysuru Palace
  {
    id: 'loc-mysuru',
    name: 'Mysuru Palace',
    city: 'Mysuru',
    state: 'Karnataka',
    country: 'India',
    latitude: 12.3051,
    longitude: 76.6552,
    description: 'Grand royal residence of the Wadiyar dynasty, illuminated by 100,000 light bulbs on weekends with serene heritage avenues.',
    timezone: 'Asia/Kolkata',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 10. Mumbai
  {
    id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    name: 'Mumbai (Marine Drive & Gateway)',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    latitude: 19.0760,
    longitude: 72.8777,
    description: 'The commercial powerhouse of India, featuring Queen’s Necklace at Marine Drive, Gateway of India, and vibrant coastal culture.',
    timezone: 'Asia/Kolkata',
    population: 20667656,
    area_km2: 603,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 11. Pune
  {
    id: 'loc-pune',
    name: 'Pune (Shaniwar Wada & Osho)',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    latitude: 18.5204,
    longitude: 73.8567,
    description: 'Cultural hub of Maharashtra with Maratha historical forts, educational institutions, and pleasant Western Ghats gateway.',
    timezone: 'Asia/Kolkata',
    population: 7400000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 12. Goa
  {
    id: 'loc-goa',
    name: 'Goa (Baga & Calangute Coast)',
    city: 'Panaji',
    state: 'Goa',
    country: 'India',
    latitude: 15.2993,
    longitude: 74.1240,
    description: 'World-famous beach destination with golden sands, Portuguese architecture, water sports, and vibrant tourist beach shacks.',
    timezone: 'Asia/Kolkata',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 13. Kochi & Alleppey
  {
    id: 'loc-kochi',
    name: 'Kochi & Alleppey Backwaters',
    city: 'Kochi',
    state: 'Kerala',
    country: 'India',
    latitude: 9.9312,
    longitude: 76.2673,
    description: 'Serene backwater paradise in Kerala featuring traditional houseboats, Chinese fishing nets in Fort Kochi, and Ayurvedic wellness.',
    timezone: 'Asia/Kolkata',
    population: 2100000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 14. Munnar
  {
    id: 'loc-munnar',
    name: 'Munnar Tea Hills',
    city: 'Munnar',
    state: 'Kerala',
    country: 'India',
    latitude: 10.0889,
    longitude: 77.0595,
    description: 'Breathtaking hill station in the Western Ghats with sprawling tea plantations, mist-covered valleys, and trekking trails.',
    timezone: 'Asia/Kolkata',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 15. New Delhi
  {
    id: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
    name: 'Delhi (India Gate & Red Fort)',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    latitude: 28.6139,
    longitude: 77.2090,
    description: 'The historic and political capital of India, filled with monumental Mughal architecture, vibrant bazaars, and world-class metro.',
    timezone: 'Asia/Kolkata',
    population: 32941000,
    area_km2: 1484,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 16. Agra (Taj Mahal)
  {
    id: 'loc-agra',
    name: 'Agra (Taj Mahal)',
    city: 'Agra',
    state: 'Uttar Pradesh',
    country: 'India',
    latitude: 27.1751,
    longitude: 78.0421,
    description: 'Home to the magnificent white marble Taj Mahal (New7Wonders of the World), Agra Fort, and rich Mughal craftsmanship.',
    timezone: 'Asia/Kolkata',
    population: 2200000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 17. Jaipur
  {
    id: 'loc-jaipur',
    name: 'Jaipur (Hawa Mahal & Amer Fort)',
    city: 'Jaipur',
    state: 'Rajasthan',
    country: 'India',
    latitude: 26.9124,
    longitude: 75.7873,
    description: 'The Pink City of Rajasthan, famous for royal palaces, hill fortresses, colorful textile markets, and regal hospitality.',
    timezone: 'Asia/Kolkata',
    population: 3900000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 18. Udaipur
  {
    id: 'loc-udaipur',
    name: 'Udaipur (City Palace & Lake Pichola)',
    city: 'Udaipur',
    state: 'Rajasthan',
    country: 'India',
    latitude: 24.5854,
    longitude: 73.7125,
    description: 'The Venice of the East, famed for Lake Pichola, floating Taj Lake Palace, and romantic Aravali mountain landscapes.',
    timezone: 'Asia/Kolkata',
    population: 650000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 19. Varanasi
  {
    id: 'loc-varanasi',
    name: 'Varanasi (Ganga Ghats & Kashi)',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    country: 'India',
    latitude: 25.3176,
    longitude: 82.9739,
    description: 'One of the world’s oldest continuously inhabited cities on the sacred Ganges River, known for evening Ganga Aarti rituals.',
    timezone: 'Asia/Kolkata',
    population: 1700000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 20. Amritsar
  {
    id: 'loc-amritsar',
    name: 'Amritsar (Golden Temple)',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
    latitude: 31.6200,
    longitude: 74.8765,
    description: 'Spiritual epicenter of Sikhism, housing the revered Harmandir Sahib (Golden Temple), community langar, and Wagah Border ceremony.',
    timezone: 'Asia/Kolkata',
    population: 1400000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 21. Kolkata
  {
    id: 'loc-kolkata',
    name: 'Kolkata (Victoria Memorial)',
    city: 'Kolkata',
    state: 'West Bengal',
    country: 'India',
    latitude: 22.5726,
    longitude: 88.3639,
    description: 'The City of Joy, famous for Victoria Memorial, Howrah Bridge, colonial architecture, tramways, and rich literary heritage.',
    timezone: 'Asia/Kolkata',
    population: 14974000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 22. Shimla & Manali
  {
    id: 'loc-shimla-manali',
    name: 'Shimla & Manali (Himalayas)',
    city: 'Manali',
    state: 'Himachal Pradesh',
    country: 'India',
    latitude: 32.2432,
    longitude: 77.1892,
    description: 'Iconic Himalayan mountain retreat with snow-clad peaks, Solang Valley adventure sports, and scenic Rohtang Pass.',
    timezone: 'Asia/Kolkata',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

// ---- Demo Safety Ratings for all 22+ Locations ----

export const DEMO_SAFETY_RATINGS: Record<string, SafetyRating> = {
  // Chennai
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890': {
    id: 'sr-1',
    location_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    overall_score: 72,
    crime_score: 68,
    weather_score: 75,
    hazard_score: 70,
    community_score: 78,
    political_stability_score: 74,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  // Marina Beach
  'e5f6a7b8-c9d0-1234-efab-345678901234': {
    id: 'sr-marina',
    location_id: 'e5f6a7b8-c9d0-1234-efab-345678901234',
    overall_score: 75,
    crime_score: 70,
    weather_score: 80,
    hazard_score: 75,
    community_score: 80,
    political_stability_score: 76,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  // Mahabalipuram
  'loc-mahabalipuram': {
    id: 'sr-mahabs',
    location_id: 'loc-mahabalipuram',
    overall_score: 88,
    crime_score: 86,
    weather_score: 88,
    hazard_score: 85,
    community_score: 92,
    political_stability_score: 90,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  // Nellore
  'loc-nellore': {
    id: 'sr-nellore',
    location_id: 'loc-nellore',
    overall_score: 80,
    crime_score: 78,
    weather_score: 82,
    hazard_score: 80,
    community_score: 84,
    political_stability_score: 82,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  // Tirupati
  'loc-tirupati': {
    id: 'sr-tirupati',
    location_id: 'loc-tirupati',
    overall_score: 92,
    crime_score: 90,
    weather_score: 92,
    hazard_score: 90,
    community_score: 95,
    political_stability_score: 94,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  // Visakhapatnam
  'loc-vizag': {
    id: 'sr-vizag',
    location_id: 'loc-vizag',
    overall_score: 82,
    crime_score: 80,
    weather_score: 84,
    hazard_score: 82,
    community_score: 85,
    political_stability_score: 84,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  // Hyderabad
  'loc-hyderabad': {
    id: 'sr-hyd',
    location_id: 'loc-hyderabad',
    overall_score: 76,
    crime_score: 72,
    weather_score: 78,
    hazard_score: 75,
    community_score: 80,
    political_stability_score: 78,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  // Bengaluru
  'd4e5f6a7-b8c9-0123-defa-234567890123': {
    id: 'sr-4',
    location_id: 'd4e5f6a7-b8c9-0123-defa-234567890123',
    overall_score: 78,
    crime_score: 74,
    weather_score: 80,
    hazard_score: 76,
    community_score: 82,
    political_stability_score: 80,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  // Mysuru
  'loc-mysuru': {
    id: 'sr-mysuru',
    location_id: 'loc-mysuru',
    overall_score: 85,
    crime_score: 84,
    weather_score: 86,
    hazard_score: 84,
    community_score: 88,
    political_stability_score: 86,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  // Mumbai
  'b2c3d4e5-f6a7-8901-bcde-f12345678901': {
    id: 'sr-2',
    location_id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    overall_score: 69,
    crime_score: 65,
    weather_score: 72,
    hazard_score: 68,
    community_score: 74,
    political_stability_score: 71,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  // Pune
  'loc-pune': {
    id: 'sr-pune',
    location_id: 'loc-pune',
    overall_score: 79,
    crime_score: 76,
    weather_score: 82,
    hazard_score: 78,
    community_score: 80,
    political_stability_score: 80,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  // Goa
  'loc-goa': {
    id: 'sr-goa',
    location_id: 'loc-goa',
    overall_score: 84,
    crime_score: 80,
    weather_score: 85,
    hazard_score: 84,
    community_score: 88,
    political_stability_score: 86,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  // Kochi
  'loc-kochi': {
    id: 'sr-kochi',
    location_id: 'loc-kochi',
    overall_score: 86,
    crime_score: 84,
    weather_score: 86,
    hazard_score: 85,
    community_score: 90,
    political_stability_score: 88,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  // Munnar
  'loc-munnar': {
    id: 'sr-munnar',
    location_id: 'loc-munnar',
    overall_score: 90,
    crime_score: 92,
    weather_score: 88,
    hazard_score: 86,
    community_score: 94,
    political_stability_score: 92,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  // Delhi
  'c3d4e5f6-a7b8-9012-cdef-123456789012': {
    id: 'sr-3',
    location_id: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
    overall_score: 65,
    crime_score: 60,
    weather_score: 70,
    hazard_score: 65,
    community_score: 68,
    political_stability_score: 72,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  // Agra
  'loc-agra': {
    id: 'sr-agra',
    location_id: 'loc-agra',
    overall_score: 74,
    crime_score: 70,
    weather_score: 74,
    hazard_score: 72,
    community_score: 78,
    political_stability_score: 76,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  // Jaipur
  'loc-jaipur': {
    id: 'sr-jaipur',
    location_id: 'loc-jaipur',
    overall_score: 81,
    crime_score: 78,
    weather_score: 82,
    hazard_score: 80,
    community_score: 84,
    political_stability_score: 82,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  // Udaipur
  'loc-udaipur': {
    id: 'sr-udaipur',
    location_id: 'loc-udaipur',
    overall_score: 89,
    crime_score: 88,
    weather_score: 88,
    hazard_score: 88,
    community_score: 92,
    political_stability_score: 90,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  // Varanasi
  'loc-varanasi': {
    id: 'sr-varanasi',
    location_id: 'loc-varanasi',
    overall_score: 73,
    crime_score: 70,
    weather_score: 72,
    hazard_score: 70,
    community_score: 78,
    political_stability_score: 76,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  // Amritsar
  'loc-amritsar': {
    id: 'sr-amritsar',
    location_id: 'loc-amritsar',
    overall_score: 87,
    crime_score: 86,
    weather_score: 86,
    hazard_score: 85,
    community_score: 92,
    political_stability_score: 88,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  // Kolkata
  'loc-kolkata': {
    id: 'sr-kolkata',
    location_id: 'loc-kolkata',
    overall_score: 71,
    crime_score: 68,
    weather_score: 72,
    hazard_score: 70,
    community_score: 75,
    political_stability_score: 72,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  // Shimla & Manali
  'loc-shimla-manali': {
    id: 'sr-shimla-manali',
    location_id: 'loc-shimla-manali',
    overall_score: 91,
    crime_score: 94,
    weather_score: 85,
    hazard_score: 88,
    community_score: 95,
    political_stability_score: 94,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
};

// ---- Demo Safety Alerts ----

export const DEMO_ALERTS: SafetyAlert[] = [
  {
    id: 'alert-1',
    location_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    title: 'Heavy Rainfall Warning',
    description: 'IMD has issued heavy rainfall warning for Chennai coastal areas. Avoid low-lying zones and beach areas during high tide.',
    severity: 'moderate',
    alert_type: 'weather',
    is_active: true,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    location: { id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', name: 'Chennai City', city: 'Chennai' },
  },
  {
    id: 'alert-2',
    location_id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    title: 'High Tide Advisory Mumbai Coast',
    description: 'High tide expected along Mumbai coastline. Stay away from Marine Drive and Juhu Beach after 6 PM.',
    severity: 'high',
    alert_type: 'weather',
    is_active: true,
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    location: { id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901', name: 'Mumbai City', city: 'Mumbai' },
  },
  {
    id: 'alert-3',
    location_id: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
    title: 'Air Quality Alert Delhi',
    description: 'AQI in Delhi has reached Unhealthy levels (AQI: 185). Wear masks outdoors.',
    severity: 'moderate',
    alert_type: 'health',
    is_active: true,
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    location: { id: 'c3d4e5f6-a7b8-9012-cdef-123456789012', name: 'Delhi', city: 'New Delhi' },
  },
];

// ---- Demo Incidents ----

export const DEMO_INCIDENTS: IncidentReport[] = [
  {
    id: 'inc-1',
    reporter_id: 'usr-1',
    location_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    category: 'theft',
    title: 'Pickpocketing reported near Chennai Central Station',
    description: 'Phone snatching incident occurred near gate 3 during evening rush hour.',
    severity: 'medium',
    status: 'verified',
    latitude: 13.0820,
    longitude: 80.2750,
    address: 'Near Gate 3, Chennai Central Railway Station',
    incident_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    verified_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    reporter: { id: 'usr-1', name: 'Verified Tourist', verification_status: 'verified' },
  },
  {
    id: 'inc-2',
    reporter_id: 'usr-2',
    location_id: 'e5f6a7b8-c9d0-1234-efab-345678901234',
    category: 'scam',
    title: 'Overcharging by horse ride operators at Marina Beach',
    description: 'Operators demanding 3x the agreed price after the ride concluded.',
    severity: 'low',
    status: 'verified',
    latitude: 13.0510,
    longitude: 80.2830,
    address: 'Marina Beach Promenade near Gandhi Statue',
    incident_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    verified_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    reporter: { id: 'usr-2', name: 'Priya Sharma', verification_status: 'verified' },
  },
  {
    id: 'inc-3',
    reporter_id: 'usr-3',
    location_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    category: 'road_hazard',
    title: 'Waterlogging & traffic bottleneck on Anna Salai',
    description: 'Heavy rain caused 1 foot waterlogging near Thousand Lights junction.',
    severity: 'medium',
    status: 'pending',
    latitude: 13.0600,
    longitude: 80.2500,
    address: 'Anna Salai near Thousand Lights Mosque',
    incident_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    reporter: { id: 'usr-3', name: 'Rahul M.', verification_status: 'verified' },
  },
];

// ---- Demo Emergency Contacts ----

export const DEMO_EMERGENCY_CONTACTS: EmergencyContact[] = [
  {
    id: 'ec-1',
    location_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    name: 'Chennai Police Control Room',
    phone: '100',
    type: 'police',
    address: 'Vepery, Chennai, Tamil Nadu 600007',
    latitude: 13.0850,
    longitude: 80.2650,
    is_24x7: true,
    is_verified: true,
    organization: 'Greater Chennai Police Department',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ec-2',
    location_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    name: 'Government General Hospital (RGGGH)',
    phone: '044-25305000',
    type: 'hospital',
    address: 'EVR Periyar Salai, Park Town, Chennai 600003',
    latitude: 13.0810,
    longitude: 80.2780,
    is_24x7: true,
    is_verified: true,
    organization: 'Rajiv Gandhi Government General Hospital',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ec-3',
    location_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    name: 'Tamil Nadu Tourist Helpline',
    phone: '1800-4253-1111',
    type: 'tourist_helpline',
    address: 'Tamil Nadu Tourism Complex, Wallajah Road, Chennai',
    latitude: 13.0680,
    longitude: 80.2750,
    is_24x7: true,
    is_verified: true,
    organization: 'Tamil Nadu Tourism Development Corporation',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

// ---- Demo Chat Messages ----

export const DEMO_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-1',
    sender_id: 'usr-1',
    region_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    message: 'Hello everyone! Is Marina Beach safe to visit around 8 PM with family?',
    is_system_message: false,
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    sender: { id: 'usr-1', name: 'David (Tourist)' },
  },
  {
    id: 'msg-2',
    sender_id: 'usr-2',
    region_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    message: 'Yes, the main promenade near Gandhi statue is well-lit and police patrol is active till 10 PM. Just stay away from unlit dark corners near the water.',
    is_system_message: false,
    created_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    sender: { id: 'usr-2', name: 'Karthik (Local Guide)' },
  },
  {
    id: 'msg-3',
    sender_id: 'usr-3',
    region_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    message: 'Can confirm! I was there yesterday with my family, very safe atmosphere with lots of food stalls.',
    is_system_message: false,
    created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    sender: { id: 'usr-3', name: 'Ananya S.' },
  },
];

// ---- Profiles ----

export const DEMO_TOURIST_PROFILE: Profile = {
  id: 'usr-demo-tourist',
  name: 'Demo Tourist',
  email: 'tourist@safewander.demo',
  phone: '+91 9876543210',
  role: 'tourist',
  verification_status: 'verified',
  emergency_contact_name: 'Priya Sharma (Sister)',
  emergency_contact_phone: '+91 9876543200',
  preferred_language: 'en',
  is_safety_mode_active: false,
  checkin_interval_minutes: 30,
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
};

export const DEMO_ADMIN_PROFILE: Profile = {
  id: 'usr-demo-admin',
  name: 'Authority Operations Admin',
  email: 'admin@safewander.demo',
  phone: '+91 9876543299',
  role: 'admin',
  verification_status: 'verified',
  emergency_contact_name: 'Command Center Dispatch',
  emergency_contact_phone: '112',
  preferred_language: 'en',
  is_safety_mode_active: false,
  checkin_interval_minutes: 15,
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
};

export const DEMO_SOS_ALERTS: SOSAlert[] = [];
