// ============================================================
// Demo / Mock data for development and presentations
// Used when Supabase is not configured or DEMO_MODE=true
// ============================================================

import type {
  Location,
  SafetyRating,
  SafetyAlert,
  IncidentReport,
  EmergencyContact,
  LocalRecommendation,
  ChatMessage,
  Profile,
  SOSAlert,
} from '@/types';

// ---- Comprehensive 22+ Famous Destinations in India ----

export const DEMO_LOCATIONS: Location[] = [
  // 1. Chennai City
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    name: 'Chennai City',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 13.0827,
    longitude: 80.2707,
    description: 'The cultural capital of South India, known for classical music, Dravidian temples, and long sandy beaches.',
    timezone: 'Asia/Kolkata',
    population: 10971108,
    area_km2: 426,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 2. Marina Beach
  {
    id: 'e5f6a7b8-c9d0-1234-efab-345678901234',
    name: 'Marina Beach',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 13.0499,
    longitude: 80.2824,
    description: 'One of the longest natural urban beaches in the world, stretching over 13 km with coastal food stalls and heritage statues.',
    timezone: 'Asia/Kolkata',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 3. Mahabalipuram
  {
    id: 'loc-mahabalipuram',
    name: 'Mahabalipuram Shore Temple',
    city: 'Mahabalipuram',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 12.6269,
    longitude: 80.1927,
    description: 'UNESCO World Heritage site featuring 7th-century rock-cut monuments, Pancha Rathas, and the iconic coastal Shore Temple.',
    timezone: 'Asia/Kolkata',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 4. Nellore
  {
    id: 'loc-nellore',
    name: 'Nellore',
    city: 'Nellore',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 14.4426,
    longitude: 79.9865,
    description: 'Historic city on the banks of Penna River, famous for Sri Ranganathaswamy Temple, Mypadu Beach, and rich agricultural heritage.',
    timezone: 'Asia/Kolkata',
    population: 600000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 5. Tirupati
  {
    id: 'loc-tirupati',
    name: 'Tirupati (Tirumala)',
    city: 'Tirupati',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 13.6288,
    longitude: 79.4192,
    description: 'World-renowned spiritual city at the foot of Seshachalam Hills, home to Sri Venkateswara Temple with round-the-clock pilgrim security.',
    timezone: 'Asia/Kolkata',
    population: 459985,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 6. Visakhapatnam
  {
    id: 'loc-vizag',
    name: 'Visakhapatnam (Vizag)',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 17.6868,
    longitude: 83.2185,
    description: 'Scenic port city known for RK Beach, INS Kursura Submarine Museum, Kailasagiri hill park, and Rushikonda Beach.',
    timezone: 'Asia/Kolkata',
    population: 2300000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 7. Hyderabad
  {
    id: 'loc-hyderabad',
    name: 'Hyderabad (Charminar & Hi-Tech City)',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    latitude: 17.3850,
    longitude: 78.4867,
    description: 'City of Pearls blending historic monuments like Golconda Fort and Charminar with cyber tech corridors and famous Hyderabadi Biryani.',
    timezone: 'Asia/Kolkata',
    population: 10500000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 8. Bengaluru
  {
    id: 'd4e5f6a7-b8c9-0123-defa-234567890123',
    name: 'Bengaluru City',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    latitude: 12.9716,
    longitude: 77.5946,
    description: 'The Silicon Valley of India, known for pleasant weather, lush green gardens (Lalbagh, Cubbon Park), and bustling cosmopolitan nightlife.',
    timezone: 'Asia/Kolkata',
    population: 13193000,
    area_km2: 741,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 9. Mysuru Palace
  {
    id: 'loc-mysuru',
    name: 'Mysuru Palace',
    city: 'Mysuru',
    state: 'Karnataka',
    country: 'India',
    latitude: 12.3051,
    longitude: 76.6552,
    description: 'Grand royal residence of the Wadiyar dynasty, illuminated by 100,000 light bulbs on weekends with serene heritage avenues.',
    timezone: 'Asia/Kolkata',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 10. Mumbai
  {
    id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    name: 'Mumbai (Marine Drive & Gateway)',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    latitude: 19.0760,
    longitude: 72.8777,
    description: 'The commercial powerhouse of India, featuring Queen’s Necklace at Marine Drive, Gateway of India, and vibrant coastal culture.',
    timezone: 'Asia/Kolkata',
    population: 20667656,
    area_km2: 603,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 11. Pune
  {
    id: 'loc-pune',
    name: 'Pune (Shaniwar Wada & Osho)',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    latitude: 18.5204,
    longitude: 73.8567,
    description: 'Cultural hub of Maharashtra with Maratha historical forts, educational institutions, and pleasant Western Ghats gateway.',
    timezone: 'Asia/Kolkata',
    population: 7400000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 12. Goa
  {
    id: 'loc-goa',
    name: 'Goa (Baga & Calangute Coast)',
    city: 'Panaji',
    state: 'Goa',
    country: 'India',
    latitude: 15.2993,
    longitude: 74.1240,
    description: 'World-famous beach destination with golden sands, Portuguese architecture, water sports, and vibrant tourist beach shacks.',
    timezone: 'Asia/Kolkata',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 13. Kochi & Alleppey
  {
    id: 'loc-kochi',
    name: 'Kochi & Alleppey Backwaters',
    city: 'Kochi',
    state: 'Kerala',
    country: 'India',
    latitude: 9.9312,
    longitude: 76.2673,
    description: 'Serene backwater paradise in Kerala featuring traditional houseboats, Chinese fishing nets in Fort Kochi, and Ayurvedic wellness.',
    timezone: 'Asia/Kolkata',
    population: 2100000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 14. Munnar
  {
    id: 'loc-munnar',
    name: 'Munnar Tea Hills',
    city: 'Munnar',
    state: 'Kerala',
    country: 'India',
    latitude: 10.0889,
    longitude: 77.0595,
    description: 'Breathtaking hill station in the Western Ghats with sprawling tea plantations, mist-covered valleys, and trekking trails.',
    timezone: 'Asia/Kolkata',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 15. New Delhi
  {
    id: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
    name: 'Delhi (India Gate & Red Fort)',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    latitude: 28.6139,
    longitude: 77.2090,
    description: 'The historic and political capital of India, filled with monumental Mughal architecture, vibrant bazaars, and world-class metro.',
    timezone: 'Asia/Kolkata',
    population: 32941000,
    area_km2: 1484,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 16. Agra (Taj Mahal)
  {
    id: 'loc-agra',
    name: 'Agra (Taj Mahal)',
    city: 'Agra',
    state: 'Uttar Pradesh',
    country: 'India',
    latitude: 27.1751,
    longitude: 78.0421,
    description: 'Home to the magnificent white marble Taj Mahal (New7Wonders of the World), Agra Fort, and rich Mughal craftsmanship.',
    timezone: 'Asia/Kolkata',
    population: 2200000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 17. Jaipur
  {
    id: 'loc-jaipur',
    name: 'Jaipur (Hawa Mahal & Amer Fort)',
    city: 'Jaipur',
    state: 'Rajasthan',
    country: 'India',
    latitude: 26.9124,
    longitude: 75.7873,
    description: 'The Pink City of Rajasthan, famous for royal palaces, hill fortresses, colorful textile markets, and regal hospitality.',
    timezone: 'Asia/Kolkata',
    population: 3900000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 18. Udaipur
  {
    id: 'loc-udaipur',
    name: 'Udaipur (City Palace & Lake Pichola)',
    city: 'Udaipur',
    state: 'Rajasthan',
    country: 'India',
    latitude: 24.5854,
    longitude: 73.7125,
    description: 'The Venice of the East, famed for Lake Pichola, floating Taj Lake Palace, and romantic Aravali mountain landscapes.',
    timezone: 'Asia/Kolkata',
    population: 650000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 19. Varanasi
  {
    id: 'loc-varanasi',
    name: 'Varanasi (Ganga Ghats & Kashi)',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    country: 'India',
    latitude: 25.3176,
    longitude: 82.9739,
    description: 'One of the world’s oldest continuously inhabited cities on the sacred Ganges River, known for evening Ganga Aarti rituals.',
    timezone: 'Asia/Kolkata',
    population: 1700000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 20. Amritsar
  {
    id: 'loc-amritsar',
    name: 'Amritsar (Golden Temple)',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
    latitude: 31.6200,
    longitude: 74.8765,
    description: 'Spiritual epicenter of Sikhism, housing the revered Harmandir Sahib (Golden Temple), community langar, and Wagah Border ceremony.',
    timezone: 'Asia/Kolkata',
    population: 1400000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 21. Kolkata
  {
    id: 'loc-kolkata',
    name: 'Kolkata (Victoria Memorial)',
    city: 'Kolkata',
    state: 'West Bengal',
    country: 'India',
    latitude: 22.5726,
    longitude: 88.3639,
    description: 'The City of Joy, famous for Victoria Memorial, Howrah Bridge, colonial architecture, tramways, and rich literary heritage.',
    timezone: 'Asia/Kolkata',
    population: 14974000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  // 22. Shimla & Manali
  {
    id: 'loc-shimla-manali',
    name: 'Shimla & Manali (Himalayas)',
    city: 'Manali',
    state: 'Himachal Pradesh',
    country: 'India',
    latitude: 32.2432,
    longitude: 77.1892,
    description: 'Iconic Himalayan mountain retreat with snow-clad peaks, Solang Valley adventure sports, and scenic Rohtang Pass.',
    timezone: 'Asia/Kolkata',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

// ---- Safety Ratings for all 22+ Locations ----

export const DEMO_SAFETY_RATINGS: Record<string, SafetyRating> = {
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890': {
    id: 'sr-1',
    location_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    overall_score: 72,
    crime_score: 68,
    weather_score: 75,
    hazard_score: 70,
    community_score: 78,
    political_stability_score: 74,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  'e5f6a7b8-c9d0-1234-efab-345678901234': {
    id: 'sr-marina',
    location_id: 'e5f6a7b8-c9d0-1234-efab-345678901234',
    overall_score: 75,
    crime_score: 70,
    weather_score: 80,
    hazard_score: 75,
    community_score: 80,
    political_stability_score: 76,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  'loc-mahabalipuram': {
    id: 'sr-mahabs',
    location_id: 'loc-mahabalipuram',
    overall_score: 88,
    crime_score: 86,
    weather_score: 88,
    hazard_score: 85,
    community_score: 92,
    political_stability_score: 90,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  'loc-nellore': {
    id: 'sr-nellore',
    location_id: 'loc-nellore',
    overall_score: 80,
    crime_score: 78,
    weather_score: 82,
    hazard_score: 80,
    community_score: 84,
    political_stability_score: 82,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  'loc-tirupati': {
    id: 'sr-tirupati',
    location_id: 'loc-tirupati',
    overall_score: 92,
    crime_score: 90,
    weather_score: 92,
    hazard_score: 90,
    community_score: 95,
    political_stability_score: 94,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  'loc-vizag': {
    id: 'sr-vizag',
    location_id: 'loc-vizag',
    overall_score: 82,
    crime_score: 80,
    weather_score: 84,
    hazard_score: 82,
    community_score: 85,
    political_stability_score: 84,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  'loc-hyderabad': {
    id: 'sr-hyd',
    location_id: 'loc-hyderabad',
    overall_score: 76,
    crime_score: 72,
    weather_score: 78,
    hazard_score: 75,
    community_score: 80,
    political_stability_score: 78,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  'd4e5f6a7-b8c9-0123-defa-234567890123': {
    id: 'sr-4',
    location_id: 'd4e5f6a7-b8c9-0123-defa-234567890123',
    overall_score: 78,
    crime_score: 74,
    weather_score: 80,
    hazard_score: 76,
    community_score: 82,
    political_stability_score: 80,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  'loc-mysuru': {
    id: 'sr-mysuru',
    location_id: 'loc-mysuru',
    overall_score: 85,
    crime_score: 84,
    weather_score: 86,
    hazard_score: 84,
    community_score: 88,
    political_stability_score: 86,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  'b2c3d4e5-f6a7-8901-bcde-f12345678901': {
    id: 'sr-2',
    location_id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    overall_score: 69,
    crime_score: 65,
    weather_score: 72,
    hazard_score: 68,
    community_score: 74,
    political_stability_score: 71,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  'loc-pune': {
    id: 'sr-pune',
    location_id: 'loc-pune',
    overall_score: 79,
    crime_score: 76,
    weather_score: 82,
    hazard_score: 78,
    community_score: 80,
    political_stability_score: 80,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  'loc-goa': {
    id: 'sr-goa',
    location_id: 'loc-goa',
    overall_score: 84,
    crime_score: 80,
    weather_score: 85,
    hazard_score: 84,
    community_score: 88,
    political_stability_score: 86,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  'loc-kochi': {
    id: 'sr-kochi',
    location_id: 'loc-kochi',
    overall_score: 86,
    crime_score: 84,
    weather_score: 86,
    hazard_score: 85,
    community_score: 90,
    political_stability_score: 88,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  'loc-munnar': {
    id: 'sr-munnar',
    location_id: 'loc-munnar',
    overall_score: 90,
    crime_score: 92,
    weather_score: 88,
    hazard_score: 86,
    community_score: 94,
    political_stability_score: 92,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  'c3d4e5f6-a7b8-9012-cdef-123456789012': {
    id: 'sr-3',
    location_id: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
    overall_score: 65,
    crime_score: 60,
    weather_score: 70,
    hazard_score: 65,
    community_score: 68,
    political_stability_score: 72,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  'loc-agra': {
    id: 'sr-agra',
    location_id: 'loc-agra',
    overall_score: 74,
    crime_score: 70,
    weather_score: 74,
    hazard_score: 72,
    community_score: 78,
    political_stability_score: 76,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  'loc-jaipur': {
    id: 'sr-jaipur',
    location_id: 'loc-jaipur',
    overall_score: 81,
    crime_score: 78,
    weather_score: 82,
    hazard_score: 80,
    community_score: 84,
    political_stability_score: 82,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  'loc-udaipur': {
    id: 'sr-udaipur',
    location_id: 'loc-udaipur',
    overall_score: 89,
    crime_score: 88,
    weather_score: 88,
    hazard_score: 88,
    community_score: 92,
    political_stability_score: 90,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  'loc-varanasi': {
    id: 'sr-varanasi',
    location_id: 'loc-varanasi',
    overall_score: 73,
    crime_score: 70,
    weather_score: 72,
    hazard_score: 70,
    community_score: 78,
    political_stability_score: 76,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  'loc-amritsar': {
    id: 'sr-amritsar',
    location_id: 'loc-amritsar',
    overall_score: 87,
    crime_score: 86,
    weather_score: 86,
    hazard_score: 85,
    community_score: 92,
    political_stability_score: 88,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  'loc-kolkata': {
    id: 'sr-kolkata',
    location_id: 'loc-kolkata',
    overall_score: 71,
    crime_score: 68,
    weather_score: 72,
    hazard_score: 70,
    community_score: 75,
    political_stability_score: 72,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
  'loc-shimla-manali': {
    id: 'sr-shimla-manali',
    location_id: 'loc-shimla-manali',
    overall_score: 91,
    crime_score: 94,
    weather_score: 85,
    hazard_score: 88,
    community_score: 95,
    political_stability_score: 94,
    calculated_at: new Date().toISOString(),
    is_current: true,
  },
};

// ---- Comprehensive Alerts across India (Heatwaves, Storms, Crowds, AQI) ----

export const DEMO_ALERTS: SafetyAlert[] = [
  // 1. Chennai
  {
    id: 'alert-chennai-1',
    location_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    title: 'Coastal High Tide Warning (Chennai)',
    description: 'IMD has issued heavy surf warning for Marina & Elliot beaches. Avoid deep water swimming after 5 PM.',
    severity: 'moderate',
    alert_type: 'weather',
    is_active: true,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    location: { id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', name: 'Chennai City', city: 'Chennai' },
  },
  // 2. Nellore
  {
    id: 'alert-nellore-1',
    location_id: 'loc-nellore',
    title: '☀️ IMD Severe Heatwave Advisory (Nellore District)',
    description: 'Daytime temperatures expected to touch 41.5°C in Nellore and surrounding coastal plains. Stay hydrated, avoid direct sun exposure between 12 PM - 3:30 PM, and carry water.',
    severity: 'high',
    alert_type: 'weather',
    is_active: true,
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    location: { id: 'loc-nellore', name: 'Nellore', city: 'Nellore' },
  },
  // 3. Tirupati
  {
    id: 'alert-tirupati-1',
    location_id: 'loc-tirupati',
    title: '🙏 Heavy Pilgrim Rush & Ghat Road Vigilance (Tirumala)',
    description: 'High footfall at Sri Venkateswara Temple. Ghat road speed limit is strictly enforced at 30 km/h with automated CCTV monitoring.',
    severity: 'moderate',
    alert_type: 'traffic',
    is_active: true,
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    location: { id: 'loc-tirupati', name: 'Tirupati (Tirumala)', city: 'Tirupati' },
  },
  // 4. Visakhapatnam
  {
    id: 'alert-vizag-1',
    location_id: 'loc-vizag',
    title: '🌊 Rip Current Warning (RK Beach & Rushikonda)',
    description: 'Strong rip currents reported along RK Beach. Lifeguard flags are RED in unpatrolled sections. Swim only in designated zones.',
    severity: 'high',
    alert_type: 'natural_disaster',
    is_active: true,
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    location: { id: 'loc-vizag', name: 'Visakhapatnam (Vizag)', city: 'Visakhapatnam' },
  },
  // 5. Hyderabad
  {
    id: 'alert-hyd-1',
    location_id: 'loc-hyderabad',
    title: '☀️ Afternoon Heatwave Advisory (Hyderabad & Secunderabad)',
    description: 'Dry heat advisory issued across Telangana. Peak heat index reaches 40°C. Hydration booths active across Charminar and Hussain Sagar.',
    severity: 'moderate',
    alert_type: 'weather',
    is_active: true,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    location: { id: 'loc-hyderabad', name: 'Hyderabad', city: 'Hyderabad' },
  },
  // 6. Bengaluru
  {
    id: 'alert-blr-1',
    location_id: 'd4e5f6a7-b8c9-0123-defa-234567890123',
    title: '🌧️ Evening Thunderstorm & Waterlogging Advisory',
    description: 'Pre-monsoon localized showers expected in Outer Ring Road and Koramangala. Moderate traffic delays expected.',
    severity: 'low',
    alert_type: 'weather',
    is_active: true,
    created_at: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    location: { id: 'd4e5f6a7-b8c9-0123-defa-234567890123', name: 'Bengaluru City', city: 'Bengaluru' },
  },
  // 7. Mumbai
  {
    id: 'alert-mum-1',
    location_id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    title: '🌊 High Tide Advisory (Mumbai Coastline)',
    description: 'High tide of 4.4 meters expected along Marine Drive and Bandra Bandstand at 6:15 PM. Police barricades deployed along promenade edge.',
    severity: 'high',
    alert_type: 'weather',
    is_active: true,
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    location: { id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901', name: 'Mumbai City', city: 'Mumbai' },
  },
  // 8. Goa
  {
    id: 'alert-goa-1',
    location_id: 'loc-goa',
    title: '🚩 Monsoon High Tide & Rough Seas Warning (Goa Beaches)',
    description: 'Red flags hoisted at Baga, Calangute, and Anjuna. Water sports suspended temporarily due to high swells.',
    severity: 'high',
    alert_type: 'natural_disaster',
    is_active: true,
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    location: { id: 'loc-goa', name: 'Goa', city: 'Panaji' },
  },
  // 9. Delhi
  {
    id: 'alert-del-1',
    location_id: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
    title: '😷 Air Quality Advisory (Delhi NCR)',
    description: 'AQI in Central Delhi recorded at 185 (Moderate to Poor). Sensitive groups are advised to wear N95 masks when visiting India Gate outdoors.',
    severity: 'moderate',
    alert_type: 'health',
    is_active: true,
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    location: { id: 'c3d4e5f6-a7b8-9012-cdef-123456789012', name: 'Delhi', city: 'New Delhi' },
  },
  // 10. Agra
  {
    id: 'alert-agra-1',
    location_id: 'loc-agra',
    title: '☀️ Taj Mahal Daytime Heat Advisory',
    description: 'Marble surface heat index high between 1 PM - 4 PM. Cloth shoe covers provided; carry hydration bottles.',
    severity: 'moderate',
    alert_type: 'weather',
    is_active: true,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    location: { id: 'loc-agra', name: 'Agra', city: 'Agra' },
  },
  // 11. Jaipur
  {
    id: 'alert-jaipur-1',
    location_id: 'loc-jaipur',
    title: '☀️ Desert Summer Heatwave (Jaipur & Amer)',
    description: 'Temperatures reaching 42°C in Amer Fort hills. Tourist battery shuttles available from main gates.',
    severity: 'high',
    alert_type: 'weather',
    is_active: true,
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    location: { id: 'loc-jaipur', name: 'Jaipur', city: 'Jaipur' },
  },
  // 12. Varanasi
  {
    id: 'alert-varanasi-1',
    location_id: 'loc-varanasi',
    title: '🪔 Evening Ganga Aarti Crowd Protocol (Dashashwamedh Ghat)',
    description: 'High pilgrim density for 7 PM Ganga Aarti. Follow police crowd lanes and board only authorized tourist boats.',
    severity: 'moderate',
    alert_type: 'general',
    is_active: true,
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    location: { id: 'loc-varanasi', name: 'Varanasi', city: 'Varanasi' },
  },
  // 13. Shimla & Manali
  {
    id: 'alert-shimla-1',
    location_id: 'loc-shimla-manali',
    title: '🏔️ High Altitude Fog & Road Slush Warning (Rohtang Pass)',
    description: 'Dense mountain fog and melting snow on high-altitude passes. Drive with fog lamps and adhere to 30 km/h mountain speed limits.',
    severity: 'moderate',
    alert_type: 'weather',
    is_active: true,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    location: { id: 'loc-shimla-manali', name: 'Shimla & Manali', city: 'Manali' },
  },
];

// ---- Comprehensive Location-Aware Emergency Services (Police, Hospitals, Helplines) ----

export const DEMO_EMERGENCY_CONTACTS: EmergencyContact[] = [
  // 1. Chennai
  {
    id: 'ec-chennai-police',
    location_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    name: 'Chennai Police Control Room',
    phone: '100',
    type: 'police',
    address: 'EVK Sampath Salai, Vepery, Chennai 600007',
    latitude: 13.0850,
    longitude: 80.2650,
    is_24x7: true,
    is_verified: true,
    organization: 'Greater Chennai Police Department',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ec-chennai-hospital',
    location_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    name: 'Rajiv Gandhi Government General Hospital (RGGGH)',
    phone: '044-25305000',
    type: 'hospital',
    address: 'EVR Periyar Salai, Park Town, Chennai 600003',
    latitude: 13.0810,
    longitude: 80.2780,
    is_24x7: true,
    is_verified: true,
    organization: 'RGGGH Multi-Specialty Trauma Center',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ec-chennai-helpline',
    location_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    name: 'Tamil Nadu Tourist Emergency Helpline',
    phone: '1800-4253-1111',
    type: 'tourist_helpline',
    address: 'Tamil Nadu Tourism Complex, Wallajah Road, Chennai',
    latitude: 13.0680,
    longitude: 80.2750,
    is_24x7: true,
    is_verified: true,
    organization: 'Tamil Nadu Tourism Development Corporation',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // 2. Nellore
  {
    id: 'ec-nellore-police',
    location_id: 'loc-nellore',
    name: 'Nellore District Police Control Room',
    phone: '0861-2331500',
    type: 'police',
    address: 'Dargamitta Police Headquarters, Nellore, AP 524003',
    latitude: 14.4450,
    longitude: 79.9820,
    is_24x7: true,
    is_verified: true,
    organization: 'Nellore District Police Department (AP Police)',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ec-nellore-hospital',
    location_id: 'loc-nellore',
    name: 'Government General Hospital (GGH Nellore)',
    phone: '0861-2327000',
    type: 'hospital',
    address: 'Gandhi Nagar, Near RTC Bus Stand, Nellore, AP 524001',
    latitude: 14.4410,
    longitude: 79.9880,
    is_24x7: true,
    is_verified: true,
    organization: 'GGH Nellore 24/7 Emergency & Trauma Care',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ec-nellore-helpline',
    location_id: 'loc-nellore',
    name: 'Andhra Pradesh Tourist Helpline',
    phone: '1800-425-45454',
    type: 'tourist_helpline',
    address: 'AP Tourism Facilitation Center, Nellore',
    latitude: 14.4430,
    longitude: 79.9850,
    is_24x7: true,
    is_verified: true,
    organization: 'Andhra Pradesh Tourism (APTDC)',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // 3. Tirupati
  {
    id: 'ec-tirupati-police',
    location_id: 'loc-tirupati',
    name: 'Tirupati Urban Police Control & TTD Vigilance',
    phone: '0877-2264250',
    type: 'police',
    address: 'Alipiri Road, Tirupati, Andhra Pradesh 517507',
    latitude: 13.6320,
    longitude: 79.4180,
    is_24x7: true,
    is_verified: true,
    organization: 'Tirupati Urban Police & TTD Security Command',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ec-tirupati-hospital',
    location_id: 'loc-tirupati',
    name: 'SVIMS Super Specialty Hospital Tirupati',
    phone: '0877-2287777',
    type: 'hospital',
    address: 'Alipiri Road, Tirupati, Andhra Pradesh 517507',
    latitude: 13.6350,
    longitude: 79.4150,
    is_24x7: true,
    is_verified: true,
    organization: 'Sri Venkateswara Institute of Medical Sciences',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // 4. Visakhapatnam (Vizag)
  {
    id: 'ec-vizag-police',
    location_id: 'loc-vizag',
    name: 'Visakhapatnam City Police Commissionerate',
    phone: '0891-2565454',
    type: 'police',
    address: 'Suryabagh, Visakhapatnam, Andhra Pradesh 530020',
    latitude: 17.6890,
    longitude: 83.2150,
    is_24x7: true,
    is_verified: true,
    organization: 'Visakhapatnam City Police',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ec-vizag-hospital',
    location_id: 'loc-vizag',
    name: 'King George Hospital (KGH Vizag)',
    phone: '0891-2564891',
    type: 'hospital',
    address: 'Maharanipeta, Visakhapatnam, Andhra Pradesh 530002',
    latitude: 17.6850,
    longitude: 83.2200,
    is_24x7: true,
    is_verified: true,
    organization: 'KGH 24/7 Government Trauma Center',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // 5. Hyderabad
  {
    id: 'ec-hyd-police',
    location_id: 'loc-hyderabad',
    name: 'Hyderabad City Police Command & Control',
    phone: '040-27852435',
    type: 'police',
    address: 'Banjara Hills Road No 12, Hyderabad 500034',
    latitude: 17.3900,
    longitude: 78.4800,
    is_24x7: true,
    is_verified: true,
    organization: 'Hyderabad City Police Headquarters',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ec-hyd-hospital',
    location_id: 'loc-hyderabad',
    name: 'Osmania General Hospital & NIMS',
    phone: '040-24600121',
    type: 'hospital',
    address: 'Afzal Gunj, High Court Road, Hyderabad 500012',
    latitude: 17.3800,
    longitude: 78.4750,
    is_24x7: true,
    is_verified: true,
    organization: 'Osmania General Emergency Hospital',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // 6. Bengaluru
  {
    id: 'ec-blr-police',
    location_id: 'd4e5f6a7-b8c9-0123-defa-234567890123',
    name: 'Bengaluru City Police Commissionerate',
    phone: '080-22942222',
    type: 'police',
    address: 'Infantry Road, Bengaluru, Karnataka 560001',
    latitude: 12.9750,
    longitude: 77.5980,
    is_24x7: true,
    is_verified: true,
    organization: 'Bengaluru City Police Command',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ec-blr-hospital',
    location_id: 'd4e5f6a7-b8c9-0123-defa-234567890123',
    name: 'Victoria Hospital & Bowring Hospital',
    phone: '080-26701150',
    type: 'hospital',
    address: 'Fort Road, Near City Market, Bengaluru 560002',
    latitude: 12.9650,
    longitude: 77.5850,
    is_24x7: true,
    is_verified: true,
    organization: 'Bangalore Medical College Emergency Division',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // 7. Mumbai
  {
    id: 'ec-mum-police',
    location_id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    name: 'Mumbai Police Headquarters & Control Room',
    phone: '022-22620111',
    type: 'police',
    address: 'Crawford Market, Fort, Mumbai 400001',
    latitude: 19.0720,
    longitude: 72.8750,
    is_24x7: true,
    is_verified: true,
    organization: 'Greater Mumbai Police Department',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ec-mum-hospital',
    location_id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    name: 'KEM Hospital & Lilavati Trauma Care',
    phone: '022-24107000',
    type: 'hospital',
    address: 'Acharya Donde Marg, Parel, Mumbai 400012',
    latitude: 19.0800,
    longitude: 72.8800,
    is_24x7: true,
    is_verified: true,
    organization: 'King Edward Memorial Hospital Mumbai',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // 8. Goa
  {
    id: 'ec-goa-police',
    location_id: 'loc-goa',
    name: 'Goa Tourist Police & Calangute Station',
    phone: '0832-2282215',
    type: 'police',
    address: 'Calangute - Baga Road, North Goa 403516',
    latitude: 15.3050,
    longitude: 74.1200,
    is_24x7: true,
    is_verified: true,
    organization: 'Goa Tourist Police Department',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ec-goa-hospital',
    location_id: 'loc-goa',
    name: 'Goa Medical College & Hospital (GMC)',
    phone: '0832-2458727',
    type: 'hospital',
    address: 'Bambolim, Panaji, Goa 403202',
    latitude: 15.2950,
    longitude: 74.1280,
    is_24x7: true,
    is_verified: true,
    organization: 'GMC 24/7 Government Emergency Care',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // 9. Delhi
  {
    id: 'ec-del-police',
    location_id: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
    name: 'Delhi Police Central Control Room',
    phone: '011-23490010',
    type: 'police',
    address: 'Jai Singh Road, Connaught Place, New Delhi 110001',
    latitude: 28.6200,
    longitude: 77.2100,
    is_24x7: true,
    is_verified: true,
    organization: 'Delhi Police Department',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ec-del-hospital',
    location_id: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
    name: 'AIIMS New Delhi Emergency Trauma Center',
    phone: '011-26588500',
    type: 'hospital',
    address: 'Sri Aurobindo Marg, Ansari Nagar, New Delhi 110029',
    latitude: 28.6100,
    longitude: 77.2050,
    is_24x7: true,
    is_verified: true,
    organization: 'All India Institute of Medical Sciences',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // 10. Agra
  {
    id: 'ec-agra-police',
    location_id: 'loc-agra',
    name: 'Agra Tourist Police & Taj Security',
    phone: '0562-2421204',
    type: 'police',
    address: 'Tajganj, Eastern Gate Road, Agra, UP 282001',
    latitude: 27.1780,
    longitude: 78.0450,
    is_24x7: true,
    is_verified: true,
    organization: 'Uttar Pradesh Tourist Police Force',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ec-agra-hospital',
    location_id: 'loc-agra',
    name: 'SN Medical College Hospital Agra',
    phone: '0562-2260353',
    type: 'hospital',
    address: 'Hospital Road, Agra, UP 282002',
    latitude: 27.1720,
    longitude: 78.0380,
    is_24x7: true,
    is_verified: true,
    organization: 'Sarojini Naidu Government Hospital Agra',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // 11. Jaipur
  {
    id: 'ec-jaipur-police',
    location_id: 'loc-jaipur',
    name: 'Jaipur Commissionerate Tourist Police',
    phone: '0141-2374444',
    type: 'police',
    address: 'MI Road, Near Ajmeri Gate, Jaipur 302001',
    latitude: 26.9150,
    longitude: 75.7890,
    is_24x7: true,
    is_verified: true,
    organization: 'Rajasthan Tourist Police Department',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ec-jaipur-hospital',
    location_id: 'loc-jaipur',
    name: 'SMS Hospital Jaipur (Sawai Man Singh)',
    phone: '0141-2560291',
    type: 'hospital',
    address: 'JLN Marg, Ashok Nagar, Jaipur 302004',
    latitude: 26.9090,
    longitude: 75.7820,
    is_24x7: true,
    is_verified: true,
    organization: 'Sawai Man Singh Trauma Care',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // 12. Varanasi
  {
    id: 'ec-varanasi-police',
    location_id: 'loc-varanasi',
    name: 'Varanasi Tourist Police (Ghat Security Command)',
    phone: '0542-2508000',
    type: 'police',
    address: 'Dashashwamedh Ghat Road, Varanasi 221001',
    latitude: 25.3200,
    longitude: 82.9750,
    is_24x7: true,
    is_verified: true,
    organization: 'Kashi Tourist Security Force',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ec-varanasi-hospital',
    location_id: 'loc-varanasi',
    name: 'Sir Sunderlal Hospital (BHU Varanasi)',
    phone: '0542-2307500',
    type: 'hospital',
    address: 'Banaras Hindu University Campus, Varanasi 221005',
    latitude: 25.3150,
    longitude: 82.9700,
    is_24x7: true,
    is_verified: true,
    organization: 'Institute of Medical Sciences BHU',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // 13. Shimla & Manali
  {
    id: 'ec-manali-police',
    location_id: 'loc-shimla-manali',
    name: 'Manali Tourist Police & Mountain Rescue',
    phone: '01902-252326',
    type: 'police',
    address: 'Mall Road, Manali, Himachal Pradesh 175131',
    latitude: 32.2450,
    longitude: 77.1900,
    is_24x7: true,
    is_verified: true,
    organization: 'HP Police Mountain Search & Rescue Cell',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ec-manali-hospital',
    location_id: 'loc-shimla-manali',
    name: 'Civil Hospital Manali (High Altitude Care)',
    phone: '01902-252327',
    type: 'hospital',
    address: 'Model Town, Manali, Himachal Pradesh 175131',
    latitude: 32.2400,
    longitude: 77.1850,
    is_24x7: true,
    is_verified: true,
    organization: 'Himachal Government Civil Hospital',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

// ---- Fallback Dynamic Generator to guarantee every single location has verified services ----

export function getEmergencyContactsForLocation(location: Location): EmergencyContact[] {
  const specific = DEMO_EMERGENCY_CONTACTS.filter(
    (c) => c.location_id === location.id || (c.address && c.address.includes(location.city))
  );

  if (specific.length > 0) return specific;

  // Dynamically generate accurate local services for any custom selected city
  return [
    {
      id: `ec-${location.city.toLowerCase()}-police`,
      location_id: location.id,
      name: `${location.city} Central Police Control Room`,
      phone: '100',
      type: 'police',
      address: `Police Headquarters, ${location.name}, ${location.state || 'India'}`,
      latitude: location.latitude + 0.005,
      longitude: location.longitude + 0.005,
      is_24x7: true,
      is_verified: true,
      organization: `${location.city} District Police & Security Division`,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: `ec-${location.city.toLowerCase()}-hospital`,
      location_id: location.id,
      name: `${location.city} Government General Hospital & Trauma Center`,
      phone: '108',
      type: 'hospital',
      address: `Main Hospital Road, ${location.city}, ${location.state || 'India'}`,
      latitude: location.latitude - 0.005,
      longitude: location.longitude - 0.005,
      is_24x7: true,
      is_verified: true,
      organization: `${location.city} Emergency Healthcare Trauma Unit`,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: `ec-${location.city.toLowerCase()}-helpline`,
      location_id: location.id,
      name: `${location.state || location.city} Tourist Safety Helpline`,
      phone: '1363',
      type: 'tourist_helpline',
      address: `Tourism Facilitation Desk, ${location.name}`,
      latitude: location.latitude,
      longitude: location.longitude,
      is_24x7: true,
      is_verified: true,
      organization: `National & State Tourism Assistance Center`,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
  ];
}

export function getAlertsForLocation(location: Location): SafetyAlert[] {
  const specific = DEMO_ALERTS.filter(
    (a) => a.location_id === location.id || (a.location?.city && a.location.city.toLowerCase() === location.city.toLowerCase())
  );

  if (specific.length > 0) return specific;

  // Dynamic realistic advisory for this city
  const isSouthOrCentral = ['Andhra Pradesh', 'Tamil Nadu', 'Telangana', 'Karnataka', 'Maharashtra'].includes(location.state || '');

  return [
    {
      id: `alert-${location.city.toLowerCase()}-heatwave`,
      location_id: location.id,
      title: isSouthOrCentral
        ? `☀️ IMD Daytime Heatwave Advisory (${location.city})`
        : `🌤️ Regional Weather & Safety Advisory (${location.city})`,
      description: isSouthOrCentral
        ? `Temperatures in ${location.city} reaching 39°C - 41°C during peak midday. Stay hydrated, carry water, and avoid prolonged outdoor sun exposure between 12 PM - 3:30 PM.`
        : `Favorable travel conditions in ${location.city}. Normal security precautions apply at major landmarks and markets.`,
      severity: isSouthOrCentral ? 'high' : 'low',
      alert_type: 'weather',
      is_active: true,
      created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      location: { id: location.id, name: location.name, city: location.city },
    },
    {
      id: `alert-${location.city.toLowerCase()}-tourist-vigilance`,
      location_id: location.id,
      title: `🛡️ Tourist Safety & Guide Verification Notice`,
      description: `When visiting famous attractions in ${location.name}, hire only government-certified tourist guides and book official transport to prevent overcharging.`,
      severity: 'moderate',
      alert_type: 'crime',
      is_active: true,
      created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      location: { id: location.id, name: location.name, city: location.city },
    },
  ];
}

// ---- Demo Incidents ----

export const DEMO_INCIDENTS: IncidentReport[] = [
  {
    id: 'inc-1',
    reporter_id: 'usr-1',
    location_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    category: 'theft',
    title: 'Pickpocketing reported near Chennai Central Station',
    description: 'Phone snatching incident occurred near gate 3 during evening rush hour.',
    severity: 'medium',
    status: 'verified',
    latitude: 13.0820,
    longitude: 80.2750,
    address: 'Near Gate 3, Chennai Central Railway Station',
    incident_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    verified_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    reporter: { id: 'usr-1', name: 'Verified Tourist', verification_status: 'verified' },
  },
  {
    id: 'inc-nellore-1',
    reporter_id: 'usr-2',
    location_id: 'loc-nellore',
    category: 'road_hazard',
    title: 'Potholes and road repair work near Penna River Bridge',
    description: 'Road work on the bridge approach creating slow vehicular traffic. Drive carefully.',
    severity: 'low',
    status: 'verified',
    latitude: 14.4440,
    longitude: 79.9850,
    address: 'Penna Bridge North Approach, Nellore',
    incident_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    verified_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    reporter: { id: 'usr-2', name: 'Suresh K.', verification_status: 'verified' },
  },
  {
    id: 'inc-tirupati-1',
    reporter_id: 'usr-3',
    location_id: 'loc-tirupati',
    category: 'scam',
    title: 'Unauthorized fast-darshan ticket touts outside Alipiri',
    description: 'Touts attempting to sell fake VIP passes. Only use official TTD website or counters.',
    severity: 'medium',
    status: 'verified',
    latitude: 13.6300,
    longitude: 79.4170,
    address: 'Alipiri Toll Gate, Tirupati',
    incident_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    verified_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    reporter: { id: 'usr-3', name: 'Ramesh V.', verification_status: 'verified' },
  },
];

// ---- Demo Chat Messages ----

export const DEMO_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-1',
    sender_id: 'usr-1',
    region_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    message: 'Hello everyone! Is the weather pleasant today around the beach and heritage temples?',
    is_system_message: false,
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    sender: { id: 'usr-1', name: 'David (Tourist)' },
  },
  {
    id: 'msg-2',
    sender_id: 'usr-2',
    region_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    message: 'Yes! The evening breeze is great, well-lit promenade and police patrol is active till 10 PM. Enjoy your visit!',
    is_system_message: false,
    created_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    sender: { id: 'usr-2', name: 'Karthik (Local Guide)' },
  },
];

// ---- Profiles ----

export const DEMO_TOURIST_PROFILE: Profile = {
  id: 'usr-demo-tourist',
  name: 'Demo Tourist',
  email: 'tourist@safewander.demo',
  phone: '+91 7424962369',
  role: 'tourist',
  verification_status: 'verified',
  emergency_contact_name: 'Emergency Contact (Guardian)',
  emergency_contact_phone: '7424962369',
  preferred_language: 'en',
  is_safety_mode_active: false,
  checkin_interval_minutes: 30,
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
};

export const DEMO_ADMIN_PROFILE: Profile = {
  id: 'usr-demo-admin',
  name: 'Authority Operations Admin',
  email: 'admin@safewander.demo',
  phone: '+91 9876543299',
  role: 'admin',
  verification_status: 'verified',
  emergency_contact_name: 'Command Center Dispatch',
  emergency_contact_phone: '112',
  preferred_language: 'en',
  is_safety_mode_active: false,
  checkin_interval_minutes: 15,
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
};

export const DEMO_SOS_ALERTS: SOSAlert[] = [];
